site_name: Seizure Data Processing

nav:
  - Home: index.md
  - API: references.md

theme:
  name: readthedocs
  include_sidebar: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true

